# --------------------------------------------------
# PERFORMANCE STABLE + COMPATIBLE AGP 8+
# --------------------------------------------------
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=false

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
kotlin.incremental=true

# Fix Hilt / Kapt crash
kapt.incremental.apt=false
